services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Coronavirus2020$
        ports:
            - 1433:1433
        volumes:
            - /var/lib/sqlserver/data 
    user-svc:
        image : iamkennedee/user-svc:latest
        build:
            context: .
            dockerfile: caseman.user.api/caseman.user.api/Dockerfile
        environment:
             - ASPNETCORE_ENVIRONMENT=Development
             - ASPNETCORE_URLS=http://+:80
             - ConnectionStrings__IdentityConnection=Server=sqlserver;Database=CaseManUserDb;TrustServerCertificate=true;User Id=sa;Password=Coronavirus2020$
        ports: 
            - 7000:80
        depends_on:
            - sqlserver
    role-svc:
        image : iamkennedee/role-svc:latest
        build:
            context: .
            dockerfile: caseman.role.api/Dockerfile
        environment:
             - ASPNETCORE_ENVIRONMENT=Development
             - ASPNETCORE_URLS=http://+:80
             - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CaseManRoleDb;TrustServerCertificate=true;User Id=sa;Password=Coronavirus2020$
        ports: 
            - 7001:80
        depends_on:
            - sqlserver 
    organisation-svc:
        image : iamkennedee/organisation-svc:latest
        build:
            context: .
            dockerfile: caseman.organisation.api/Dockerfile
        environment:
             - ASPNETCORE_ENVIRONMENT=Development
             - ASPNETCORE_URLS=http://+:80
             - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CaseManOrganisationDb;TrustServerCertificate=true;User Id=sa;Password=Coronavirus2020$
        ports: 
            - 7002:80
        depends_on:
            - sqlserver
    gateway-svc:
        image : iamkennedee/gateway-svc:latest
        build:
            context: .
            dockerfile: caseman.gateway.api/caseman.gateway.api/Dockerfile
        environment:
                - ASPNETCORE_ENVIRONMENT=Docker
                - ASPNETCORE_URLS=http://+:80
        ports: 
            - 6000:80 
   

    